version: '3.8'

services:
  nebula-bot:
    container_name: nebula-bot
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_JS_FILE=index.js
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
